# Generated by Django 3.0.5 on 2020-05-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=None)),
                ('deadline_date', models.DateField()),
                ('deadline_time', models.TimeField(default=None)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_subtask', models.BooleanField(default=False)),
            ],
        ),
    ]
