# Generated by Django 3.0.5 on 2020-05-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
